work_dir: ./work_dir/ntu120/xset/msg3d_bone_64frames_baseline

# feeder
feeder: feeders.feeder_ntu.Feeder
train_feeder_args:
  data_path: data/ntu120/NTU120_CSet.npz
  split: train
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 64
  normalization: False
  random_rot: True
  p_interval: [0.5, 1]
  vel: False
  bone: True

test_feeder_args:
  data_path: data/ntu120/NTU120_CSet.npz
  split: test
  window_size: 64
  p_interval: [0.95]
  vel: False
  bone: True
  debug: False

# model
model: model.msg3d.Model
model_args:
  num_class: 120
  num_point: 25
  num_person: 2
  num_gcn_scales: 13
  num_g3d_scales: 6
  graph: model.msg3d_helper.ntu_rgb_d.AdjMatrixGraph
  # graph_args:
  #   labeling_mode: 'spatial'

#optim
weight_decay: 0.0004
base_lr: 0.1
step: [30, 40]
warm_up_epoch: 5

# training
device: [0]
batch_size: 128
test_batch_size: 128
num_epoch: 50
nesterov: True

