work_dir: work_dir/ntu120/xsub/offline_acfl_joint_msg3d

# feeder
feeder: feeders.customized_feeder_ntu.Feeder
train_feeder_args:
  data_path: data/ntu/NTU60_CS.npz
  split: train
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 64
  normalization: False
  random_rot: True
  p_interval: [0.5, 1]
  vel: False
  bone: True

test_feeder_args:
  data_path: data/ntu/NTU60_CS.npz
  split: test
  window_size: 64
  p_interval: [0.95]
  vel: False
  bone: True
  debug: False

# model
target_form: joint # options: joint bone hybrid
source_sform_model: model.msg3d.Model
source_mform_model: model.msg3d.NaiveMultiModel
target_model: model.msg3d.Model
cfml_loss: model.loss.CFMLloss
model_args:
  num_class: 120
  num_point: 25
  num_person: 2
  num_gcn_scales: 13
  num_g3d_scales: 6
  graph: model.msg3d_helper.ntu_rgb_d.AdjMatrixGraph

#optim
weight_decay: 0.0004
base_lr: 0.1
step: [35, 55]
warm_up_epoch: 5

# training
device: [0]
batch_size: 128
test_batch_size: 128
num_epoch: 65
nesterov: True

source_model:
  joint_model_weights: './source_models/msg3d/ntu120/msg3d_joint_ntu120_xsub.pt'
  bone_model_weights: './source_models/msg3d/ntu120/msg3d_bone_ntu120_xsub.pt'
  hybrid_model_weights: './source_models/msg3d/ntu120/msg3d_joint_bone_ntu120_xsub.pt'
  
