work_dir: work_dir/ntu60/xview/online_acfl_shiftgcn

# feeder
feeder: feeders.customized_feeder_ntu.Feeder
train_feeder_args:
  data_path: data/ntu/NTU60_CV.npz
  split: train
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 64
  normalization: False
  random_rot: True
  p_interval: [0.5, 1]
  vel: False
  bone: True

test_feeder_args:
  data_path: data/ntu/NTU60_CV.npz
  split: test
  window_size: 64
  p_interval: [0.95]
  vel: False
  bone: True
  debug: False

# model
source_sform_model: model.shift_gcn.Model
source_mform_model: model.shift_gcn.NaiveMultiModel
cfml_loss: model.loss.CFMLloss
model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  base_channel: 64
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0004
base_lr: 0.1
step: [35, 55]
warm_up_epoch: 5

# training
device: [0]
batch_size: 128
test_batch_size: 128
num_epoch: 65
nesterov: True
